language: python

python:
    - "2.7"
    - "3.6"

env:
    - DJANGO=1.6
    - DJANGO=1.6.5
    - DJANGO=1.7
    - DJANGO=1.8.6
    - DJANGO=1.11

install:
    - pip install -q Django==$DJANGO
    - make install

script:
    - make test
