language: python

python:
    - "2.7"

env:
    - DJANGO=1.6
    - DJANGO=1.6.5
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11

install:
    - pip install -q django==$DJANGO --use-mirrors
    - make install

script:
    - make test
